version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build
      - run: dotnet pack -o out/ -c Release -p:PackageVersion=1.0.2
      - run: dotnet nuget push PredicateExtensions/out/PredicateExtensionsCore.1.0.2.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json