version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build
      - run: dotnet pack -o out/
      - run: dotnet nuget push out/PredicateExtensionsCore.1.0.0.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json